### ISSUE TITLE
Longer TTL than 7200?

### ISSUE THREAD

**Issue by martinjo** [awein/SleepProxyClient#14]
Has anyone managed to significantly increase the interval between automatic wakeups by the sleep proxy server? I'm trying to get my file server to sleep, but every two hours (or so) it wakes up whatever I set the TTL-value to.

Is this value limited on the server side, or is the client implementation lacking?

**Comment by awein** [comment]
I haven't used this code for quite some time myself now but it should have worked when I used it last a few years ago.

How did you change the value? By changing the value in the script or by using the `--ttl` option?

I noticed that `--ttl` defaults to 4500 (75 min) and not 7200 (2h) like it should be. This is probably a bug I never noticed before since I always specify a value

**Comment by martinjo** [comment]
Thanks! It seems that you are right, when setting the TTL by passing it as a parameter it seems to work. I was setting the the TTL constant in the script at first, but as you say it is overwritten during execution, which I completely missed when looking through the script.
